databases:
  - name: MaeSchreckWebsite
    databaseName: MaeSchreckWebsite
    user: MaeSchreckWebsite

services:
  - type: web
    name: MaeSchreckWebsite
    env: ruby
    repo: https://github.com/Maedevlin47/Mae_S_website.git
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MaeSchreckWebsite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
