databases:
  - name: Mae_Schreck_Website
    databaseName: Mae_Schreck_Website
    user: Mae_Schreck_Website

services:
  - type: web
    name: Mae_Schreck_Website
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Mae_Schreck_Website
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
